##############################################################################
# CircleCI 2.0 for ci-test
#
# Copyright (c) 2018 Mateusz Loskot <mateusz@loskot.net>
#
# Use, modification and distribution is subject to the Boost Software License,
# Version 1.0. (See accompanying file LICENSE_1_0.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt)
##############################################################################
version: 2.0

##############################################################################
# Docker images
##############################################################################
docker_gcc48: &docker_gcc48
  docker:
    - image: gcc:4.8
docker_gcc49: &docker_gcc49
  docker:
    - image: gcc:4.9

docker_gcc51: &docker_gcc51
  docker:
    - image: gcc:5.1
docker_gcc52: &docker_gcc52
  docker:
    - image: gcc:5.2
docker_gcc53: &docker_gcc53
  docker:
    - image: gcc:5.3
docker_gcc54: &docker_gcc54
  docker:
    - image: gcc:5.4
docker_gcc55: &docker_gcc55
  docker:
    - image: gcc:5.5

docker_gcc61: &docker_gcc61
  docker:
    - image: gcc:6.1
docker_gcc62: &docker_gcc62
  docker:
    - image: gcc:6.2
docker_gcc63: &docker_gcc63
  docker:
    - image: gcc:6.3
docker_gcc64: &docker_gcc64
  docker:
    - image: gcc:6.4

docker_gcc71: &docker_gcc71
  docker:
    - image: gcc:7.3
docker_gcc72: &docker_gcc72
  docker:
    - image: gcc:7.2
docker_gcc73: &docker_gcc73
  docker:
    - image: gcc:7.3

docker_gcc82: &docker_gcc82
  docker:
    - image: gcc:8.2

docker_clang39: &docker_clang39
  docker:
    - image: rferraro/cxx-clang:3.9

docker_clang40: &docker_clang40
  docker:
    - image: rferraro/cxx-clang:4.0

docker_clang50: &docker_clang50
  docker:
    - image: rferraro/cxx-clang:5.0

##############################################################################
# Build variants
##############################################################################
env_gcc_cxx11: &env_gcc_cxx11
  environment:
    - CXX: g++
    - CXXSTD: "11"
    - TOOLSET: gcc

env_gcc_cxx14: &env_gcc_cxx14
  environment:
    - CXX: g++
    - CXXSTD: "14"
    - TOOLSET: gcc

env_gcc_cxx17: &env_gcc_cxx17
  environment:
    - CXX: g++
    - CXXSTD: "17"
    - TOOLSET: gcc

env_gcc_cxx17: &env_gcc_cxx20
  environment:
    - CXX: g++
    - CXXSTD: "20"
    - B2_CXXSTD: "2a"
    - TOOLSET: gcc

##############################################################################
# Build configurations
##############################################################################
config_gcc48_cxx11: &config_gcc48_cxx11
  <<: *docker_gcc48
  <<: *env_gcc_cxx11

config_gcc49_cxx11: &config_gcc49_cxx11
  <<: *docker_gcc49
  <<: *env_gcc_cxx11

config_gcc82_cxx11: &config_gcc82_cxx11
  <<: *docker_gcc82
  <<: *env_gcc_cxx11

config_gcc82_cxx14: &config_gcc82_cxx14
  <<: *docker_gcc82
  <<: *env_gcc_cxx14

config_gcc82_cxx17: &config_gcc82_cxx17
  <<: *docker_gcc82
  <<: *env_gcc_cxx17

config_gcc82_cxx20: &config_gcc82_cxx20
  <<: *docker_gcc82
  <<: *env_gcc_cxx20

##############################################################################
# Workspace persistance
##############################################################################
attach_workspace: &attach_workspace
  attach_workspace:
    at: ~/project

##############################################################################
# Build steps (in alphabetical order by name of steps group)
##############################################################################
run_compiler_version: &run_compiler_version
  run:
    name: Checking compiler version
    command: |
      echo CXX=$CXX
      echo CXXSTD=$CXXSTD
      if test -n "$B2_CXXSTD"; then
        echo B2_CXXSTD=$B2_CXXSTD
      fi
      echo TOOLSET=$TOOLSET
      $TOOLSET --version

run_build_boost: &run_build_boost
  run:
    name: Building Boost
    command: |
      pwd && ls -l && cd project
      pwd && ls -l && cd boost
      ./bootstrap.sh -with-toolset=$TOOLSET || cat ./bootstrap.log
      ./b2 headers
      if test -z "$B2_CXXSTD"; then
        B2_CXXSTD=$CXXSTD
      fi
      ./b2 toolset=$TOOLSET cxxstd=$B2_CXXSTD --with-filesystem stage
      ls -l stage/lib

run_install_cmake: &run_install_cmake
  run:
    name: Install latest CMake
    command: ./project/.ci/install-cmake.sh $HOME/usr

steps_build_and_test: &steps_build_and_test
  steps:
    - *attach_workspace
    - *run_install_cmake
    - *run_compiler_version
    - *run_build_boost
    - run:
        name: Prepare build directory
        command: |
          pwd && ls -l
          cd project
          pwd && ls -l
          mkdir -p build
    - run:
        name: Run cmake
        command: |
          cd project/build
          $HOME/usr/bin/cmake -DCMAKE_CXX_STANDARD=${CXXSTD} -DCMAKE_VERBOSE_MAKEFILE=ON -DBOOST_ROOT=~/project/project/boost ..
    - run:
        name: Run cmake --build
        command: |
          cd project/build
          $HOME/usr/bin/cmake --build .
    - run:
        name: Run ctest
        command: |
          cd project/build
          $HOME/usr/bin/ctest -V --output-on-failure

##############################################################################
# Build jobs
##############################################################################
jobs:
  bootstrap_checkout:
    <<: *config_gcc82_cxx11
    steps:
      - checkout
      - run:
          name: Checkout Boost superproject
          command: |
            git clone -b master --depth 1 https://github.com/boostorg/boost.git
            cd boost
            git submodule --quiet update --init tools/build
            git submodule --quiet update --init tools/boost_install
            git submodule --quiet update --init tools/boostdep
            git submodule --quiet update --init libs/headers
            git submodule --quiet update --init libs/config
            git submodule --quiet update --init libs/filesystem
            python tools/boostdep/depinst/depinst.py filesystem
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  gcc48_cxx11:
    <<: *config_gcc48_cxx11
    <<: *steps_build_and_test

  gcc49_cxx11:
    <<: *config_gcc49_cxx11
    <<: *steps_build_and_test

  gcc82_cxx11:
    <<: *config_gcc82_cxx11
    <<: *steps_build_and_test

  gcc82_cxx11:
    <<: *config_gcc82_cxx11
    <<: *steps_build_and_test

  gcc82_cxx14:
    <<: *config_gcc82_cxx14
    <<: *steps_build_and_test

  gcc82_cxx17:
    <<: *config_gcc82_cxx17
    <<: *steps_build_and_test

  gcc82_cxx20:
    <<: *config_gcc82_cxx20
    <<: *steps_build_and_test

##############################################################################
# Workflows
##############################################################################
workflows:
  version: 2
  build-and-test:
    jobs:
      - bootstrap_checkout

      ### GCC 4.x ############################################################
      - gcc48_cxx11
          requires:
            - bootstrap_checkout
      - gcc49_cxx11
          requires:
            - bootstrap_checkout

      # - gcc82_cxx11:
      #     requires:
      #       - bootstrap_checkout
      # - gcc82_cxx14:
      #     requires:
      #       - bootstrap_checkout
      # - gcc82_cxx17:
      #     requires:
      #       - bootstrap_checkout
      # - gcc82_cxx20:
      #     requires:
      #       - bootstrap_checkout

# notify:
#   webhooks:
#     - url: https://webhooks.gitter.im/e/9538066016dc0f9b6511
